version: '3'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    volumes: 
      - "./src:/var/www/html"
      - /tmp/xdebug:/tmp/xdebug
    ports:
      - 80:80
      - 9000:9000
    depends_on:
      - mysql
      - mongo
    environment:
      MYSQL_DSN: "mysql:host=mysql;dbname=mydatabase"
      MYSQL_USER: ${MYSQL_USER:-myuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mypassword}
      MONGO_DSN: "mongodb://mongo:27017"
      XDEBUG_ENABLED: "1"
  
  # frontend-prod:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile-prod
  #   volumes: 
  #     - "./src:/var/www/html"
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - mysql
  #     - mongo
  #   environment:
  #     MYSQL_DSN: "mysql:host=mysql;dbname=mydatabase"
  #     MYSQL_USER: ${MYSQL_USER:-myuser}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mypassword}
  #     MONGO_DSN: "mongodb://mongo:27017"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myrootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql-data:/var/lib/mysql
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8085:80
        
  mongo:
    image: mongo:4.2.0
    container_name: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
        - MONGO_INITDB_DATABASE=mydatabase
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongodb/db:/data/db
      - ./database/mongodb/dev.archive:/Databases/dev.archive
      - ./database/mongodb/production:/Databases/production

  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"