# Use the oificial PHP and Apache image
FROM php:7.0.33-apache

# Install MySQL drivers
RUN apt-get update
RUN docker-php-ext-install pdo pdo_mysql mysqli

COPY init.sql /docker-entrypoint-initdb.d/init.sql
RUN chmod -R 775 /docker-entrypoint-initdb.d

# Install MongoDB drivers
RUN apt-get update && \
    apt-get install -y libssl-dev && \
    pecl install mongodb-1.5.5 && \
    docker-php-ext-enable mongodb

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer require --working-dir=/var/www/html mongodb/mongodb

# Copy application source
COPY src /var/www/html
RUN chown -R www-data:www-data /var/www/html

# Set the document root to /var/www/html
ENV APACHE_DOCUMENT_ROOT /var/www/html
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf \
    && sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Working Directory
WORKDIR /var/www/html

# Expose port 80
EXPOSE 80

